name = "maplestar-guild-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "guild-db"
database_id = "3742ee92-8693-4e3c-afd7-156b14a0c539"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "maplestar-guild-images"

[dev]
port = 8787
local_protocol = "http"
