name = "maplestar-guild-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "guild-db"
database_id = "83397dc6-14ed-40b1-bdf3-fc9f90dfa783"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "maplestar-guild-images"

[triggers]
crons = ["0 * * * *"]

[dev]
port = 8787
local_protocol = "http"
